FROM python:3.9.4

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /usr/src/api

RUN pip install --upgrade pip

COPY /api/requirements.txt /usr/src/api

RUN pip install -r requirements.txt
