version: "3"

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: "./Dockerfile.django"
    container_name: "django"
    working_dir: "/usr/src/api"
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./api:/usr/src/api
